name: go release it

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with: 
        go-version: '1.25.1'

    - name: Build
      run: |
        mkdir -p dist
        go build -o dist/myapp .
      
    - name: bump version and create tag
      id: tag
      uses: anothrnick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: minor_fix

    - name: create github release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.new_tag }}
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
